# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='closed_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='open_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooking_style',
            field=models.CharField(choices=[(b'frying', b'Fried'), (b'boiling', b'Boiled'), (b'baking', b'Baked'), (b'roasting', b'Roasted'), (b'instant', b'Microwaved')], max_length=8),
        ),
    ]
