# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0005_auto_20160422_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_inst',
            name='use_bestbef',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource_inst',
            name='best_before',
            field=models.BooleanField(default=True),
        ),
    ]
