# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 16:50
from __future__ import unicode_literals

from django.db import migrations

def transfer_units(apps, schema_editor):
    Resource_Inst   = apps.get_model('mealy', 'Resource_Inst')
    Unit            = apps.get_model('mealy', 'Unit')

    for inst in Resource_Inst.objects.all():
        unit, isnew = Unit.objects.get_or_create(shortcode=inst.units_original,
                            verbose_name=inst.units_original,
                            verbose_plural="%ss"%inst.units_original)
        inst.orig_unit = unit
        inst.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0007_new_units_model'),
    ]

    operations = [
        migrations.RunPython(transfer_units),
    ]
