# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0008_transfer_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_inst',
            name='units_original',
        ),
    ]
