# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0009_remove_units_char_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_inst',
            name='orig_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mealy.Unit'),
        ),
        migrations.AlterField(
            model_name='resource_inst',
            name='orig_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealy.Unit'),
        ),
    ]
