# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 17:12
from __future__ import unicode_literals

from django.db import migrations

def transfer_units(apps, schema_editor):
    Standard_Inst   = apps.get_model('mealy', 'Standard_Inst')
    Unit            = apps.get_model('mealy', 'Unit')

    for inst in Standard_Inst.objects.all():
        try:
            unit = Unit.objects.get(shortcode=inst.orig_units)
        except Unit.DoesNotExist:
            unit = Unit(shortcode=inst.orig_units, verbose_name=inst.orig_units,
                        verbose_plural="%ss"%inst.orig_units)
            unit.save()
        inst.orig_unit = unit
        inst.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0010_change_std_units'),
    ]

    operations = [
        migrations.RunPython(transfer_units),
    ]
