# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0011_transfer_units_std_inst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard_inst',
            name='orig_units',
        ),
        migrations.AlterField(
            model_name='standard_inst',
            name='orig_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealy.Unit'),
        ),
    ]
