# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0012_remove_units_char_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_inst',
            name='is_relative',
            field=models.BooleanField(default=False),
        ),
    ]
