# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealy', '0013_standard_inst_is_relative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooking_style',
            field=models.CharField(choices=[('frying', 'Fried'), ('boiling', 'Boiled'), ('baking', 'Baked'), ('roasting', 'Roasted'), ('uncooked', 'Processed'), ('instant', 'Microwaved')], max_length=8),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cons_time',
            field=models.DateTimeField(verbose_name='time eaten'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Tea', 'Tea'), ('Supper', 'Supper'), ('Snack', 'Snack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='resource_inst',
            name='best_bef_date',
            field=models.DateTimeField(verbose_name='best before date'),
        ),
        migrations.AlterField(
            model_name='resource_inst',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='purchase date'),
        ),
    ]
